# utils/data_utils.py
"""
Data loading and preprocessing utilities.

CRITICAL FIX applied here vs the original utils.py:
  ✅  StandardScaler is now fit ONLY on X_train — NEVER on the full dataset.
      The original code called scaler.fit_transform(X) before any split,
      which leaks test-set statistics into the scaler and produces
      optimistically-biased accuracy numbers.

  ✅  Clients load pre-partitioned NPZ files (generated by partitioner.py)
      and therefore never access the global diabetes.csv at runtime.

  ✅  pos_weight is computed from training labels only so the loss function
      handles class imbalance without data-leakage.
"""

import os
import numpy as np
import pandas as pd
import torch
import joblib
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from typing import Tuple

# ── Path constants ────────────────────────────────────────────────────────────
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH   = os.path.join(_ROOT, "diabetes.csv")
SCALER_PATH = os.path.join(_ROOT, "artifacts", "scaler.pkl")


# ─────────────────────────────────────────────────────────────────────────────
# Raw data loading
# ─────────────────────────────────────────────────────────────────────────────

def load_raw_data(data_path: str = DATA_PATH) -> Tuple[np.ndarray, np.ndarray]:
    """
    Read the Pima Indians Diabetes CSV and return feature matrix + label vector.

    Columns expected (8 features + 1 target):
        Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin,
        BMI, DiabetesPedigreeFunction, Age, Outcome
    """
    df = pd.read_csv(data_path)
    X = df.drop("Outcome", axis=1).values.astype(np.float32)
    y = df["Outcome"].values.astype(np.float32)
    return X, y


# ─────────────────────────────────────────────────────────────────────────────
# Class imbalance
# ─────────────────────────────────────────────────────────────────────────────

def compute_pos_weight(y_train: np.ndarray) -> float:
    """
    Compute pos_weight for BCEWithLogitsLoss.

    Formula:  pos_weight = num_negative / num_positive

    Effect: upweights the minority (diabetic) class so that a missed
    diabetes diagnosis (false negative) is penalised more heavily than a
    false alarm (false positive) — critical for healthcare applications.

    Must be derived from TRAINING labels only to avoid leakage.
    """
    num_pos = float(np.sum(y_train == 1))
    num_neg = float(np.sum(y_train == 0))
    if num_pos == 0:
        return 1.0
    return num_neg / num_pos


# ─────────────────────────────────────────────────────────────────────────────
# Global split (used by centralized baseline & partitioner)
# ─────────────────────────────────────────────────────────────────────────────

def prepare_global_splits(
    data_path:    str   = DATA_PATH,
    test_size:    float = 0.15,   # 15 % → server held-out test
    val_size:     float = 0.10,   # 10 % → centralised validation
    random_state: int   = 42,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray,
           np.ndarray, np.ndarray, np.ndarray, float]:
    """
    Load → stratified split → scale (train-only fit) → save scaler.

    Returns
    -------
    X_train, X_val, X_test, y_train, y_val, y_test, pos_weight
    """
    X, y = load_raw_data(data_path)

    # Step 1 – carve out test set first (stratified to preserve class ratio)
    X_temp, X_test, y_temp, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state, stratify=y
    )

    # Step 2 – split remaining into train / val
    val_ratio = val_size / (1.0 - test_size)
    X_train, X_val, y_train, y_val = train_test_split(
        X_temp, y_temp,
        test_size=val_ratio,
        random_state=random_state,
        stratify=y_temp,
    )

    # Step 3 – fit scaler on TRAIN ONLY
    scaler  = StandardScaler()
    X_train = scaler.fit_transform(X_train)   # learns mean/std from train
    X_val   = scaler.transform(X_val)          # applies train statistics
    X_test  = scaler.transform(X_test)         # applies train statistics

    # Step 4 – persist scaler for inference
    os.makedirs(os.path.dirname(SCALER_PATH), exist_ok=True)
    joblib.dump(scaler, SCALER_PATH)

    # Step 5 – class weight from training labels only
    pos_weight = compute_pos_weight(y_train)

    return X_train, X_val, X_test, y_train, y_val, y_test, pos_weight


# ─────────────────────────────────────────────────────────────────────────────
# DataLoader helpers
# ─────────────────────────────────────────────────────────────────────────────

def make_dataloader(
    X:          np.ndarray,
    y:          np.ndarray,
    batch_size: int  = 32,
    shuffle:    bool = True,
    drop_last:  bool = False,
) -> DataLoader:
    """Convert numpy arrays to a PyTorch DataLoader."""
    X_t = torch.tensor(X, dtype=torch.float32)
    y_t = torch.tensor(y, dtype=torch.float32).view(-1, 1)
    ds  = TensorDataset(X_t, y_t)
    return DataLoader(ds, batch_size=batch_size, shuffle=shuffle,
                      drop_last=drop_last, pin_memory=False)


# ─────────────────────────────────────────────────────────────────────────────
# Client data loading (pre-partitioned NPZ files)
# ─────────────────────────────────────────────────────────────────────────────

def load_client_data(
    client_id:  int,
    data_dir:   str,
    batch_size: int = 32,
    num_clients: int = 0,   # kept for API compatibility; unused here
) -> Tuple[DataLoader, DataLoader, float]:
    """
    Load the pre-partitioned dataset for a specific client.

    Each client has its own NPZ file produced by partitioner.py:
        data/federated/client_{client_id}.npz

    The file contains:
        X_train, y_train  – local training split (already scaled)
        X_val,   y_val    – local validation split (already scaled)

    Returns
    -------
    trainloader, valloader, pos_weight
    """
    client_file = os.path.join(data_dir, f"client_{client_id}.npz")
    if not os.path.exists(client_file):
        raise FileNotFoundError(
            f"Client data file not found: {client_file}\n"
            f"Generate datasets first:\n"
            f"  python train_federated.py --mode prepare "
            f"--num_clients <N> --alpha 0.5"
        )

    data      = np.load(client_file)
    X_train   = data["X_train"].astype(np.float32)
    y_train   = data["y_train"].astype(np.float32)
    X_val     = data["X_val"].astype(np.float32)
    y_val     = data["y_val"].astype(np.float32)

    pos_weight   = compute_pos_weight(y_train)
    trainloader  = make_dataloader(X_train, y_train, batch_size=batch_size, shuffle=True)
    valloader    = make_dataloader(X_val,   y_val,   batch_size=batch_size, shuffle=False)

    return trainloader, valloader, pos_weight


# ─────────────────────────────────────────────────────────────────────────────
# Server test-set loading
# ─────────────────────────────────────────────────────────────────────────────

def load_server_test_data(data_dir: str, batch_size: int = 64) -> DataLoader:
    """
    Load the server's held-out test set for global model evaluation.

    This dataset is:
      - Reserved BEFORE federated partitioning (clients never see it).
      - Scaled using the same scaler fit on the federated training pool.
      - Used by the server after every aggregation round to compute
        AUC-ROC, F1, Recall, etc. on a truly unseen population.
    """
    test_file = os.path.join(data_dir, "server_test.npz")
    if not os.path.exists(test_file):
        raise FileNotFoundError(
            f"Server test file not found: {test_file}\n"
            f"Generate datasets first:\n"
            f"  python train_federated.py --mode prepare"
        )
    data = np.load(test_file)
    return make_dataloader(
        data["X_test"].astype(np.float32),
        data["y_test"].astype(np.float32),
        batch_size=batch_size,
        shuffle=False,
    )
